version: '2'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      WEBPORT: 8000
      STATIC: /public
   
  postgres:
    build: ./db
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data: {}